#ifndef GAMEINSTANCE_HPP
#define GAMEINSTANCE_HPP

#include <vector>

#include "boards.hpp"
#include "tiles.hpp"
#include "pieces.hpp"
#include "types.hpp"

// An instance of a game. Basically contains everything needed to run the core mechanics of the game
class GameInstance {
    public:
        // Constructor
        GameInstance(unsigned int seed, BiomeType biome, MissionType mission, int octave, bool hasRoad);

        // Public members of GameInstance,
        // Public because information will be displayed to player
        bool playerWin; // Not this one, this will do stuff in run
        BiomeType biome;
        MissionType mission; // The mission type of the game
        bool road; // Determines whether a board will generate a road
        int octave; // Used for perlin noise octaves
        int boardWidth; // Generated by seed, used to make the board
        int boardHeight; 

    // Private Members of GameInstance, make private later
        Board board;
        std::vector<Piece> playerPieces;
        std::vector<Piece> enemyPieces;
        unsigned int seed;

        // When a GameInstance is selected, makeGame actually generates the board
        void makeGame(std::vector<Piece> runPieces, std::vector<Piece> enemyPieces);

        // Two methods to get tiles, one from an (x,y) coordinate, and another from a piece object.
        Tile * getTile(int x, int y);
        Tile * getPieceTile(Piece * piece);

        // Methods over pieces
        std::vector<Tile *> getValidMoves(Piece * piece);
        bool movePiece(Piece * piece, int x, int y);
        bool addPiece(Piece * piece, int x, int y);
        bool pieceExists(Piece * piece);
};



#endif
