#ifndef GAMEINSTANCE_HPP
#define GAMEINSTANCE_HPP

#include <vector>

#include "tiles.hpp"
#include "pieces.hpp"
#include "types.hpp"

// A move structure, denoting the origin tile and target tile of a move
struct Move {
    Tile * from;
    Tile * to;
};

// An instance of a game. Basically contains everything needed to run the core mechanics of the game
class GameInstance {
    public:
        // Constructor
        GameInstance(unsigned int seed, BiomeType biome, MissionType mission, int octave, bool hasRoad);

        // Public members of GameInstance,
        // Public because information will be displayed to player
        bool playerWin; // Not this one, this will do stuff in run
        BiomeType biome;
        MissionType mission; // The mission type of the game
        bool hasRoad; // Determines whether a board will generate a road
        int octave; // Used for perlin noise octaves
        int boardWidth; // Generated by seed, used to make the board
        int boardHeight; 

        // Private Members of GameInstance, make private later
        std::vector<Tile> board;
        std::vector<Piece *> playerPieces;
        std::vector<Piece *> enemyPieces;
        unsigned int seed;

        // When a GameInstance is selected, makeGame actually generates the board
        void makeGame(std::vector<Piece *> runPieces, std::vector<Piece *> enemyPieces);

        // Two methods to get tiles, one from an (x,y) coordinate, and another from a piece object.
        Tile * getTile(int x, int y);
        Tile * getPieceTile(Piece * piece);

        // Methods over pieces
        std::vector<Move> getValidMoves(Piece * piece);
        bool movePiece(Piece * piece, int x, int y);
        bool addPiece(Piece * piece, int x, int y);
        bool pieceExists(Piece * piece);
};

#endif
